pluralNoun1 = input("Plural Noun: ")
personInRoom = input("Person In Room (Last Name): ")
adj1 = input("Adjective: ")
noun1 = input("Noun: ")
noun2 = input("Noun: ")
partOfTheBody1 = input("Part of the body: ")
partOfTheBody2 = input("Part of the body: ")
pluralNoun2 = input("Plural Noun: ")
noun3 = input("Noun: ")
noun4 = input("Noun: ")
exclamation = input("Exclamation: ")
noun5 = input("Noun: ")
noun6 = input("Noun: ")
noun7 = input("Noun: ")
verb = input("Verb: ")
noun8 = input("Noun: ")
adj2 = input("Adjective: ")
noun9 = input("Noun: ")

print()
print("MAD LIBS: A VISIT TO THE DENTIST")
print("A one act play to be performed by two " + pluralNoun1 + " in this room")
print("PATIENT: Thank you so very much for seeing me, Doctor ")
print(personInRoom + ", on such " + adj1 + " notice.")
print("DENTIST: What is your problem, young " + noun1 + "?")
print("PATIENT: I have a pain in my upper " + noun2 + ", which")
print("is giving me a severe " + partOfTheBody1 + "ache.")
print("DENTIST: Let me take a look. Open your " + partOfTheBody2 + " wide.")
print("Good. Now I'm going to tap your " + pluralNoun2 + " with my " + noun3 + ".")
print("PATIENT: Shouldn't you give me a/an " + noun4 + " killer?")
print("DENTIST: It's not necessary yet. " + exclamation + "! I think I see")
print("a/an " + noun5 + " in your upper " + noun6)
print("PATIENT: Are you going to pull my " + noun7 + " out?")
print("DENTIST: No I'm going to " + verb + " your tooth and put it")
print("a temporary " + noun8 + ".")
print("PATIENT: When do I come back for the " + adj2 + " filling?")
print("DENTIST: A day after I cash your " + noun9 + ".")